x-logging: &logging
  driver: json-file
  options:
    max-size: "20m"
    max-file: "5"
    compress: "true"

services:
  postgres:
    container_name: postgres
    logging: *logging
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB_FILE: /run/secrets/db
      POSTGRES_USER_FILE: /run/secrets/user
      POSTGRES_PASSWORD_FILE: /run/secrets/password
    command: -p ${POSTGRES_PORT}
    volumes:
      - ${LOKOT_DIR}/postgres:/run/secrets:ro
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    logging: *logging
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - ${LOKOT_DIR}/redis:/run/secrets:ro
    command: >
      redis-server /run/secrets/redis.conf
      --port 0
      --tls-port ${REDIS_PORT}
      --tls-cert-file /run/secrets/redis.crt
      --tls-key-file /run/secrets/redis.key
      --tls-ca-cert-file /run/secrets/ca.crt
      --tls-auth-clients no

  minio:
    container_name: minio
    logging: *logging
    image: minio/minio
    restart: unless-stopped
    command: server /data --address ":${MINIO_PORT}" --console-address ":${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/root_user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/root_password
    volumes:
      - ${LOKOT_DIR}/minio:/run/secrets:ro
      - miniodata:/data

  backend:
    container_name: backend
    logging: *logging
    build: .
    restart: unless-stopped
    env_file:
      - .env
      - .env.backend
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      MINIO_HOST: minio
      BACKEND_TLS_CERT_PATH: /run/secrets/backend.crt
      BACKEND_TLS_KEY_PATH: /run/secrets/backend.key
      REDIS_TLS_CA_PATH: /run/secrets/ca.crt
      FRONTEND_DIST_PATH: /app/static
    volumes:
      - ${LOKOT_DIR}/backend:/run/secrets:ro
    depends_on:
      - postgres
      - redis
      - minio

  cloudflared:
    container_name: cloudflared
    logging: *logging
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      TUNNEL_TOKEN_FILE: /run/secrets/token
    volumes:
      - ${LOKOT_DIR}/cloudflared:/run/secrets:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
  miniodata:
