package rs.moma.janus.lokot.cli

import rs.moma.janus.lokot.LokotException
import rs.moma.janus.lokot.externals.wipe
import rs.moma.janus.lokot.io.secretsRoot
import rs.moma.janus.lokot.schema.Delivery
import rs.moma.janus.lokot.schema.Schema
import rs.moma.janus.lokot.files.Files

fun runUnlock(arguments: List<String>): Int {
    val initialising = arguments.any { it == "-i" || it == "--init" }
    arguments.firstOrNull { it != "-i" && it != "--init" }?.let {
        println("'$it' is not something 'lokot unlock' understands. A remote target comes later.")
        return 1
    }

    val unlocked = unlockVault("use") ?: return 1
    unlocked.kek.wipe()

    val schema = try {
        Schema.parse(unlocked.body.schema)
    } catch (failure: Exception) {
        println("The schema inside $VAULT_FILE will not parse: ${failure.message}")
        return 1
    }

    // Everything is checked before anything is written, so a refusal leaves no half-written root.
    schema.check(unlocked.values)?.let {
        println("$VAULT_FILE does not match its schema: $it")
        println("Put it right with 'lokot edit'. Nothing was written.")
        return 1
    }

    val chosen = schema.deliveries.filter { initialising || !it.onlyAtInit }

    val root = secretsRoot()
    clear(root)
    if (!Files.makeDirectory(root)) {
        println("Cannot create $root, so there is nowhere to put the files.")
        return 1
    }

    chosen.groupBy { it.service }.forEach { (service, deliveries) ->
        if (!Files.makeDirectory("$root/$service")) {
            println("Cannot create $root/$service.")
            return 1
        }
        deliveries.forEach { write(root, it, unlocked.values.getValue(it.secret)) }
    }

    if (schema.compose.isNotEmpty()) {
        val environment = try {
            renderEnvironment(root, schema.compose, unlocked.values)
        } catch (failure: LokotException) {
            println(failure.message)
            return 1
        }
        Files.writeBytes(ENV_FILE, environment.encodeToByteArray())
    }

    println()
    println("Wrote ${pluralize(chosen.size, "file")} under $root")
    if (schema.compose.isNotEmpty()) println("Wrote ${pluralize(schema.compose.size + 1, "line")} to $ENV_FILE")
    println("LOKOT_DIR=$root")
    val held = schema.deliveries.size - chosen.size
    if (held > 0) println("${pluralize(held, "more file")} would be written by 'lokot unlock -i', on a first run.")
    println("Run 'lokot lock' when the containers are up; they read their files once, at start.")
    return 0
}

fun runLock(): Int {
    val root = secretsRoot()
    val removed = clear(root)
    println(if (removed == 0) "Nothing to remove; $root is already gone." else "Removed $removed from $root.")

    if (Files.readText(ENV_FILE)?.startsWith(GENERATED) == true && Files.delete(ENV_FILE))
        println("Removed $ENV_FILE.")
    return 0
}

fun renderEnvironment(root: String, names: List<String>, values: Map<String, String>): String {
    val entries = listOf("LOKOT_DIR" to root) + names.map { it to values.getValue(it) }
    entries.forEach { (name, value) ->
        if (value.any { it == '\n' || it == '\r' })
            throw LokotException("'$name' spans more than one line, which a compose .env cannot hold.")
    }
    val header = """
        $GENERATED on ${utcNow()} - DO NOT EDIT
        # your changes will be overwritten on the next unlock
        # edit with 'lokot edit' instead
    """.trimIndent()
    return "$header\n\n" + entries.joinToString("\n") { (name, value) -> "$name=$value" } + "\n"
}

private const val GENERATED = "# generated by lokot"

private fun write(root: String, delivery: Delivery, value: String) {
    Files.writeSecret("$root/${delivery.path}", (delivery.prefix + value).encodeToByteArray())
}

private fun clear(root: String): Int {
    var removed = 0
    Files.list(root).forEach { entry ->
        val path = "$root/$entry"
        Files.list(path).forEach { if (Files.delete("$path/$it")) removed++ }
        if (!Files.deleteDirectory(path) && Files.delete(path)) removed++
    }
    Files.deleteDirectory(root)
    return removed
}
