[versions]
kotlinx-coroutines="1.11.0"
lettuce = "7.6.0.RELEASE"
postgresql = "42.7.13"
bouncycastle = "1.82"
hikaricp = "7.1.0"
logback = "1.5.35"
exposed = "1.4.0"
kotlin = "2.4.0"
minio = "9.0.3"
koin = "4.2.2"

[libraries]
kotlinx-coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version.ref = "kotlinx-coroutines" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
bouncycastle-pkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
lettuce-core = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
minio = { module = "io.minio:minio", version.ref = "minio" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
